
// (Re)Generated by UpdateVersionInfo 2.1.62 alpha (Maui) - 25.08.2025 10:55
// https://github.com/ZeProgFactory/UpdateVersionInfo
//# 2.1.64
//# 25.08.2025
//# 14:35

using System;

namespace ZPF
{
   public class VersionInfo 
   {
      // - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  -

      static VersionInfo _Current = null;

      public static VersionInfo Current
      {
         get
         {
            if (_Current == null)
            {
               _Current = new VersionInfo();
            };

            return _Current;
         }

         set
         {
            _Current = value;
         }
      }

      // - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  -

      /// <summary>
      /// Represents the version number as string
      /// </summary>
      public string sVersion { get; set; } = "2.1.64";
 
      /// <summary>
      /// Represents the version number
      /// </summary>
      public Version Version { get => new Version(sVersion); }


      /// <summary>
      /// Represents the build date part of build timestamp as string
      /// </summary>
      public string BuildOn { get; set; } = "25.08.2025";

      /// <summary>
      /// Represents the build date & time part of build timestamp as string
      /// </summary>
      public string LongBuildOn { get; set; } = "25.08.2025 14:35"; 

      public int RevisionNumber { get => Version.Revision; }


      // - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  -

      override public string ToString()
      {
         return $"{sVersion} ({LongBuildOn})";
      }

      public void SetVersion(Version version)
      {
         sVersion = version.ToString();
      }

      public void SetBuildOn(DateTime now)
      {
         BuildOn = now.ToString("dd.MM.yyyy");
         LongBuildOn = now.ToString("dd.MM.yyyy HH:mm");
      }

      // - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  - -  -
   }
}
