// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LittleHelpers
{
    internal sealed partial class Vsix
    {
        public const string Id = "ea5c68d6-cdae-4e79-bd46-2a39e95bb256";
        public const string Name = "Little Helpers";
        public const string Description = @"The easiest way to diff two files directly in Solution Explorer";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Michael Engelmann";
        public const string Tags = "compare, files, diff";
    }
}
