// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LittleHelpers
{
    internal sealed partial class Vsix
    {
        public const string Id = "D4766DA2-8D92-4404-8F8C-61B5BB42F967";
        public const string Name = "Little Helpers";
        public const string Description = @"The easiest way to diff two files directly in Solution Explorer";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Michael Engelmann";
        public const string Tags = "compare, files, diff";
    }
}
