// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LittleHelpers
{
   using System;

   /// <summary>
   /// Helper class that exposes all GUIDs used across VS Package.
   /// </summary>
   internal sealed partial class PackageGuids
   {
      public const string guidPackageString = "6e490dec-1b23-471e-8120-f164af6b268a";
      public const string guidLittleHelpersCmdSetString = "5034b97c-760a-45e5-a15d-d86dcfae06f7";
      public static Guid guidPackage = new Guid(guidPackageString);
      public static Guid guidLittleHelpersCmdSet = new Guid(guidLittleHelpersCmdSetString);
   }
   /// <summary>
   /// Helper class that encapsulates all CommandIDs uses across VS Package.
   /// </summary>
   internal sealed partial class PackageIds
   {
      public const int MyMenuGroup = 0x1020;

      public const int CmdID_DiffFiles = 0x0100;
      public const int CmdID_ProjectTool = 0x0101;
      public const int CmdID_TOF = 0x0102;
   }
}
